### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by 0xspade** [ethicalhackingplayground/ssrf-king#2]
Should also check for:

```http
GET http://burpcollab/some/endpoint HTTP/1.1
Host: example.com
...
```
or 
```http
GET @burpcollab/some/endpoint HTTP/1.1
Host: example.com
...
```
or 
```http
GET /some/endpoint HTTP/1.1
Host: example.com:80@burpcollab
...
```
or changing the host header
```http
GET /some/endpoint HTTP/1.1
Host: burpcollab
...
```
or overriding the sites
```http
GET /some/endpoint HTTP/1.1
Host: example.com
X-Forwarded-Host: burpcollab
...
```
Reference:

https://portswigger.net/research/cracking-the-lens-targeting-https-hidden-attack-surface

**Comment by ethicalhackingplayground** [comment]
Thanks so much for this enhancement. :) I will get these implemented as soon as possible.

**Comment by 0xspade** [comment]
Yep, read [albinowax presentation](https://portswigger.net/research/cracking-the-lens-targeting-https-hidden-attack-surface) first so that you have an idea. good thing you created this burp extension. I always wanted to make one but don't know how. :)

**Comment by ethicalhackingplayground** [comment]
Thanks so much. I've seen the presentation there are some cool tricks I might have in mind.

**Comment by 0xspade** [comment]
yeah yeah.. looking forward to the updates :)

**Comment by ethicalhackingplayground** [comment]
@0xspade Hey man, I've implemented the features you asked for.

I'm going to close this issue for now, if you find anything wrong with the new features
Please let me know.

Regards,
Blake.
