### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by 0xspade** [ethicalhackingplayground/ssrf-king#3]
Hey man,

So far this tool is good but anyways, upon checking the Extender Logs, I didn't see two payloads
```http
GET http://burpcollab/some/endpoint HTTP/1.1
Host: example.com
...
```
and
```http
GET @burpcollab/some/endpoint HTTP/1.1
Host: example.com
...
```

**Comment by ethicalhackingplayground** [comment]
Thanks so much man for the support. I will fix that now 👍

**Comment by ethicalhackingplayground** [comment]
Hey @0xspade ,

How's your day going I have resolved the issue, if you could give it a try that will be great.

![issue-resolved](https://user-images.githubusercontent.com/33673319/104466095-e8c6c580-5608-11eb-9146-27abf895e816.PNG)

I will close this, if you find any other issues, please open a new issue.

Thanks so much for your support.
